CREATE SEQUENCE user_id_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TRIGGER user_id_trigger
    BEFORE INSERT ON UTILISATEUR
    FOR EACH ROW
BEGIN
    SELECT user_id_seq.nextval INTO :new.USERID FROM dual;
END;

ALTER TABLE UTILISATEUR
ADD (
    IsEmailVerified NUMBER(1) DEFAULT 0 NOT NULL,
    EmailToken VARCHAR2(255)
);

CREATE SEQUENCE CANDIDATURE_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CANDIDATURE_TRG
BEFORE INSERT ON CANDIDATURE
FOR EACH ROW
BEGIN
  :NEW.ID_CANDIDATURE := CANDIDATURE_SEQ.NEXTVAL;
END;
/
